In [2]:
import pandas as pd
import requests
import io

# URL FBref Lens
url = "https://fbref.com/en/squads/fd4e0f7d/Lens-Stats"
headers = {'User-Agent': 'Mozilla/5.0'}

# Télécharger la page et lire tous les tableaux
response = requests.get(url, headers=headers)
response.raise_for_status()
html_io = io.StringIO(response.text)
tables = pd.read_html(html_io)

print(f"✅ {len(tables)} tableaux détectés")

# Afficher un aperçu des 5 premières lignes de chaque tableau
for idx, df in enumerate(tables):
    print(f"--- Tableau n°{idx} (lignes & colonnes brutes) ---")
    display(df.head())
    print("\n")

✅ 14 tableaux détectés
--- Tableau n°0 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Playing Time               Performance       ...  \
                  MP       Starts     Min   90s         Gls  Ast  ...
0                 33           31  2615.0  29.1         3.0  7.0  ...
1                 29           29  2543.0  28.3         0.0  1.0  ...
2                 34           27  2225.0  24.7         1.0  2.0  ...
3                 25           24  2112.0  23.5         0.0  0.0  ...
4                 31           22  1794.0  19.9         1.0  1.0  ...

  Per 90 Minutes                                                       \
             Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0           0.24  0.34  0.10   0.34  0.20  0.21   0.41  0.20     0.41
1           0.04  0.04  0.00   0.04  0.06  0.07   0.13  0.06     0.13
2           0.08  0.12  0.04   0.12  0.12  0.11   0.23  0.12     0.23
3           0.00  0.00  0.00   0.00  0.03  0.03   0.06  0.03     0.06
4           0.05  0.10  0.05   0.10  0.23  0.07   0.31  0.23     0.31

  Unnamed: 33_level_0
              Matches
0             Matches
1             Matches
2             Matches
3             Matches
4             Matches

[5 rows x 34 columns]

--- Tableau n°1 (lignes & colonnes brutes) ---

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Opp Formation,Referee,Match Report,Notes
0,2024-08-18,17:00,Ligue 1,Matchweek 1,Sun,Away,W,1,0,Angers,1.2,0.4,58.0,14811,Brice Samba,3-4-1-2,5-3-2,Thomas Léonard,Match Report,NaN
1,2024-08-22,21:00,Conf Lg,Play-off round,Thu,Home,W,2,1,gr Panathinaikos,NaN,NaN,NaN,37232,Brice Samba,3-4-1-2,4-2-3-1,Gergő Bogár,Match Report,Leg 1 of 2
2,2024-08-25,15:00,Ligue 1,Matchweek 2,Sun,Home,W,2,0,Brest,2.9,0.9,52.0,37435,Brice Samba,3-4-1-2,4-3-3,Jérémie Pignard,Match Report,NaN
3,2024-08-29,21:00,Conf Lg,Play-off round,Thu,Away,L,0,2,gr Panathinaikos,NaN,NaN,NaN,58500,Brice Samba,3-4-1-2,4-2-3-1,Juan Martínez,Match Report,Leg 2 of 2; Panathinaikos won
4,2024-09-01,15:00,Ligue 1,Matchweek 3,Sun,Away,D,1,1,Monaco,2.2,1.0,38.0,9030,Brice Samba,3-4-1-2,4-2-3-1,Willy Delajod,Match Report,NaN

--- Tableau n°2 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0        Brice Samba             fr FRA                 GK               30.0
1        Mathew Ryan             au AUS                 GK               32.0
2        Hervé Koffi             bf BFA                 GK               27.0
3        Squad Total                NaN                NaN               27.1
4     Opponent Total                NaN                NaN               25.9

  Playing Time                    Performance        ...                   \
            MP Starts   Min   90s          GA  GA90  ...  D   L  CS   CS%
0           15     15  1350  15.0          14  0.93  ...  6   3   7  46.7
1           14     14  1260  14.0          17  1.21  ...  1   5   6  42.9
2            5      5   450   5.0           8  1.60  ...  0   4   0   0.0
3           34     34  3060  34.0          39  1.15  ...  7  12  13  38.2
4           34     34  3060  34.0          42  1.24  ...  7  15  10  29.4

  Penalty Kicks                    Unnamed: 23_level_0
          PKatt PKA PKsv PKm Save%             Matches
0             4   4    0   0   0.0             Matches
1             3   2    1   0  33.3             Matches
2             2   2    0   0   0.0             Matches
3             9   8    1   0  11.1                 NaN
4             5   5    0   0   0.0                 NaN

[5 rows x 24 columns]

--- Tableau n°3 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0        Brice Samba             fr FRA                 GK               30.0
1        Mathew Ryan             au AUS                 GK               32.0
2        Hervé Koffi             bf BFA                 GK               27.0
3        Squad Total                NaN                NaN               27.1
4     Opponent Total                NaN                NaN               25.9

  Unnamed: 4_level_0 Goals               ... Goal Kicks                 \
                 90s    GA PKA FK CK OG  ...        Att Launch% AvgLen
0               15.0    14   4  2  3  0  ...         76    44.7   36.1
1               14.0    17   2  0  0  0  ...         66    42.4   35.3
2                5.0     8   2  0  1  0  ...         19    42.1   36.4
3               34.0    39   8  2  4  0  ...        201    34.8   31.0
4               34.0    42   5  0  6  2  ...        246    41.5   34.0

  Crosses           Sweeper                 Unnamed: 30_level_0
      Opp Stp  Stp%    #OPA #OPA/90 AvgDist             Matches
0     152  17  11.2      22    1.47    16.1             Matches
1     176  20  11.4      10    0.71    11.6             Matches
2      53   4   7.5       2    0.40     9.4             Matches
3     381  41  10.8      34    1.00     NaN                 NaN
4     580  33   5.7      48    1.41    15.8                 NaN

[5 rows x 31 columns]

--- Tableau n°4 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Standard                      ...                    \
                 90s      Gls  Sh SoT  SoT% Sh/90  ...  Dist FK PK PKatt
0               29.1        3  41  11  26.8  1.41  ...  14.3  0  0     0
1               28.3        0  27   3  11.1  0.96  ...  18.3  0  0     0
2               24.7        1  40   5  12.5  1.62  ...  20.0  0  0     0
3               23.5        0  16   4  25.0  0.68  ...  17.4  0  0     0
4               19.9        1  47  18  38.3  2.36  ...  14.7  0  0     0

  Expected                           Unnamed: 22_level_0
        xG npxG npxG/Sh G-xG np:G-xG             Matches
0      5.9  5.9    0.15 -2.9    -2.9             Matches
1      1.8  1.8    0.07 -1.8    -1.8             Matches
2      2.9  2.9    0.07 -1.9    -1.9             Matches
3      0.8  0.8    0.05 -0.8    -0.8             Matches
4      4.6  4.6    0.10 -3.6    -3.6             Matches

[5 rows x 23 columns]

--- Tableau n°5 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Total                              ...  \
                 90s   Cmp   Att  Cmp% TotDist PrgDist  ...
0               29.1  1318  1612  81.8   20594    5103  ...
1               28.3  1655  1889  87.6   27012    9960  ...
2               24.7   849  1068  79.5   11438    2865  ...
3               23.5  1133  1332  85.1   20473    8262  ...
4               19.9   732   996  73.5   10828    2837  ...

  Unnamed: 19_level_0 Unnamed: 20_level_0 Expected       Unnamed: 23_level_0  \
                  Ast                 xAG       xA A-xAG                  KP
0                   7                 6.0      5.2   1.0                  56
1                   1                 2.0      3.4  -1.0                  24
2                   2                 2.8      3.3  -0.8                  33
3                   0                 0.7      0.9  -0.7                  11
4                   1                 1.5      2.9  -0.5                  18

  Unnamed: 24_level_0 Unnamed: 25_level_0 Unnamed: 26_level_0  \
                  1/3                 PPA               CrsPA
0                  99                  29                   7
1                 157                  30                   2
2                  60                  31                   3
3                 109                  10                   2
4                  74                  29                   9

  Unnamed: 27_level_0 Unnamed: 28_level_0
                 PrgP             Matches
0                 149             Matches
1                 174             Matches
2                 116             Matches
3                 127             Matches
4                 105             Matches

[5 rows x 29 columns]

--- Tableau n°6 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Unnamed: 5_level_0 Pass Types               ...          \
                 90s                Att       Live Dead  FK  TB  ... Crs  TI
0               29.1               1612       1539   68  36   4  ...  58   8
1               28.3               1889       1744  136  70   3  ...  16  66
2               24.7               1068       1030   27  15  13  ...  30   0
3               23.5               1332       1290   38  37   2  ...  10   1
4               19.9                996        943   43   5   8  ...  75  29

      Corner Kicks         Outcomes            Unnamed: 20_level_0
   CK           In Out Str      Cmp Off Blocks             Matches
0  24            8  13   0     1318   5     33             Matches
1   0            0   0   0     1655   9     18             Matches
2  11            8   3   0      849  11     30             Matches
3   0            0   0   0     1133   4     11             Matches
4   2            0   0   0      732  10     42             Matches

[5 rows x 21 columns]

--- Tableau n°7 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0  SCA       SCA Types               ...     GCA        \
                 90s  SCA SCA90  PassLive PassDead  TO  ... Def GCA GCA90
0               29.1  109  3.75        85        9   0  ...   4  11  0.38
1               28.3   68  2.41        62        1   1  ...   1   3  0.11
2               24.7   85  3.44        63        1  11  ...   1   3  0.12
3               23.5   25  1.07        23        0   1  ...   0   0  0.00
4               19.9   53  2.66        44        0   4  ...   0   3  0.15

  GCA Types                        Unnamed: 21_level_0
   PassLive PassDead TO Sh Fld Def             Matches
0         8        0  0  3   0   0             Matches
1         3        0  0  0   0   0             Matches
2         3        0  0  0   0   0             Matches
3         0        0  0  0   0   0             Matches
4         3        0  0  0   0   0             Matches

[5 rows x 22 columns]

--- Tableau n°8 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Tackles                               ... Challenges  \
                 90s     Tkl TklW Def 3rd Mid 3rd Att 3rd  ...       Tkl%
0               29.1      90   47      42      25      23  ...       54.7
1               28.3      44   29      22      18       4  ...       57.1
2               24.7      37   26      10      22       5  ...       40.0
3               23.5      44   23      22      19       3  ...       57.5
4               19.9      22   13       3       8      11  ...       54.5

       Blocks          Unnamed: 17_level_0 Unnamed: 18_level_0  \
  Lost Blocks  Sh Pass                 Int             Tkl+Int
0   43     48   3   45                  19                 109
1   18     30  10   20                  32                  76
2   24     24   1   23                  15                  52
3   17     27  12   15                  25                  69
4   10     12   2   10                  14                  36

  Unnamed: 19_level_0 Unnamed: 20_level_0 Unnamed: 21_level_0
                  Clr                 Err             Matches
0                  28                   2             Matches
1                  70                   0             Matches
2                  18                   2             Matches
3                 122                   2             Matches
4                  25                   0             Matches

[5 rows x 22 columns]

--- Tableau n°9 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Touches                                  ... Carries  \
                 90s Touches Def Pen Def 3rd Mid 3rd Att 3rd  ... TotDist
0               29.1    1995      52     333    1028     650  ...    4501
1               28.3    2176     121     706    1150     341  ...    6893
2               24.7    1367      23     158     741     505  ...    5197
3               23.5    1594     159     629     854     117  ...    3570
4               19.9    1186      25     105     546     544  ...    2942

                               Receiving      Unnamed: 27_level_0
  PrgDist PrgC 1/3 CPA Mis Dis       Rec PrgR             Matches
0    2078   30  34   9  67  41      1361  138             Matches
1    3678   46  48   2  27  14      1514   42             Matches
2    2776   82  74  10  75  42       966   94             Matches
3    1960   18  15   0  11   3      1086    4             Matches
4    1488   44  43   7  20  22       932  170             Matches

[5 rows x 28 columns]

--- Tableau n°10 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Playing Time                   Starts  ... Team Success  \
                  MP          Min Mn/MP  Min%   90s Starts  ...         onGA
0                 33       2615.0  79.0  85.5  29.1     31  ...         32.0
1                 29       2543.0  88.0  83.1  28.3     29  ...         30.0
2                 34       2225.0  65.0  72.7  24.7     27  ...         23.0
3                 25       2112.0  84.0  69.0  23.5     24  ...         29.0
4                 31       1794.0  58.0  58.6  19.9     22  ...         21.0

                    Team Success (xG)                             \
   +/- +/-90 On-Off              onxG onxGA xG+/- xG+/-90 On-Off
0  4.0  0.14   0.34              45.2  37.7   7.4    0.26   0.44
1  9.0  0.32   1.36              45.6  33.5  12.1    0.43   1.39
2  4.0  0.16   0.27              36.4  31.9   4.5    0.18  -0.03
3 -2.0 -0.09  -0.56              34.1  32.4   1.7    0.07  -0.38
4 -3.0 -0.15  -0.58              30.4  26.2   4.2    0.21   0.04

  Unnamed: 26_level_0
              Matches
0             Matches
1             Matches
2             Matches
3             Matches
4             Matches

[5 rows x 27 columns]

--- Tableau n°11 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0   Adrien Thomasson             fr FRA                 MF               30.0
1     Facundo Medina             ar ARG                 DF               25.0
2         Andy Diouf             fr FRA                 MF               21.0
3    Jonathan Gradit             fr FRA                 DF               31.0
4     Florian Sotoca             fr FRA              FW,MF               33.0

  Unnamed: 4_level_0 Performance                     ...                       \
                 90s        CrdY CrdR 2CrdY Fls Fld  ... Int TklW PKwon PKcon
0               29.1           7    0     0  51  48  ...  19   47     0     1
1               28.3          15    1     1  29  22  ...  32   29     0     1
2               24.7           2    0     0  43  21  ...  15   26     0     1
3               23.5           4    0     0  29  16  ...  25   23     0     0
4               19.9           2    1     0  15  20  ...  14   13     0     0

           Aerial Duels            Unnamed: 21_level_0
  OG Recov          Won Lost  Won%             Matches
0  0   206           17   45  27.4             Matches
1  0   165           30   24  55.6             Matches
2  0   154           18   31  36.7             Matches
3  0    73           64   44  59.3             Matches
4  0    79           43   26  62.3             Matches

[5 rows x 22 columns]

--- Tableau n°12 (lignes & colonnes brutes) ---

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Goalkeeper,Notes
0,6,Lyon,34,17,6,11,65,46,19,57,1.68,60.3,45.7,14.6,0.43,51191,Alexandre Lacazette - 15,Lucas Perri,→ Europa League via league finish
1,7,Strasbourg,34,16,9,9,56,44,12,57,1.68,49.3,56.1,-6.9,-0.20,19378,Emanuel Emegha - 14,Đorđe Petrović,→ Conference League via league finish
2,8,Lens,34,15,7,12,42,39,3,52,1.53,51.8,45.3,6.5,0.19,37971,Neil El Aynaoui - 8,Brice Samba,NaN
3,9,Brest,34,15,5,14,52,59,-7,50,1.47,45.4,57.4,-12.0,-0.35,14536,Ludovic Ajorque - 13,Marco Bizot,NaN
4,10,Toulouse,34,11,9,14,44,43,1,42,1.24,49.1,36.8,12.4,0.36,25593,Zakaria Aboukhlal - 7,Guillaume Restes,NaN

--- Tableau n°13 (lignes & colonnes brutes) ---

  Unnamed: 0_level_0 Unnamed: 1_level_0 Home                            ...  \
                  Rk              Squad   MP   W  D  L  GF  GA  GD Pts  ...
0                  6               Lyon   17  11  2  4  37  21  16  35  ...
1                  7         Strasbourg   17  10  5  2  33  20  13  35  ...
2                  8               Lens   17   7  2  8  19  22  -3  23  ...
3                  9              Brest   17  10  3  4  31  21  10  33  ...
4                 10           Toulouse   17   5  5  7  20  22  -2  20  ...

  Away
     L  GF  GA  GD Pts Pts/MP    xG   xGA   xGD xGD/90
0    7  28  25   3  22   1.29  24.5  23.4   1.1   0.06
1    7  23  24  -1  22   1.29  24.7  29.9  -5.1  -0.30
2    4  23  17   6  29   1.71  22.8  23.5  -0.7  -0.04
3   10  21  38 -17  17   1.00  20.7  32.4 -11.7  -0.69
4    7  24  21   3  22   1.29  27.8  18.4   9.4   0.55

[5 rows x 28 columns]